#include "Languages.h"
#include <map>

namespace Enums {
    std::string languageToString(Language language) {
        static const std::map<Language, std::string> languageMap = {
            {Language::ITALIAN, "Italian"},
            {Language::ENGLISH, "English"},
            {Language::SPANISH, "Spanish"},
            {Language::FRENCH, "French"},
            {Language::GERMAN, "German"},
            {Language::PORTUGUESE, "Portuguese"},
            {Language::RUSSIAN, "Russian"},
            {Language::CHINESE, "Chinese"},
            {Language::JAPANESE, "Japanese"},
            {Language::KOREAN, "Korean"},
            {Language::ARABIC, "Arabic"},
            {Language::HINDI, "Hindi"},
            {Language::DUTCH, "Dutch"},
            {Language::SWEDISH, "Swedish"},
            {Language::NORWEGIAN, "Norwegian"},
            {Language::DANISH, "Danish"},
            {Language::FINNISH, "Finnish"},
            {Language::POLISH, "Polish"},
            {Language::CZECH, "Czech"},
            {Language::HUNGARIAN, "Hungarian"},
            {Language::ROMANIAN, "Romanian"},
            {Language::BULGARIAN, "Bulgarian"},
            {Language::GREEK, "Greek"},
            {Language::TURKISH, "Turkish"},
            {Language::HEBREW, "Hebrew"},
            {Language::PERSIAN, "Persian"},
            {Language::THAI, "Thai"},
            {Language::VIETNAMESE, "Vietnamese"},
            {Language::INDONESIAN, "Indonesian"},
            {Language::MALAY, "Malay"},
            {Language::FILIPINO, "Filipino"},
            {Language::LATIN, "Latin"},
            {Language::ANCIENT_GREEK, "Ancient Greek"},
            {Language::SANSKRIT, "Sanskrit"},
            {Language::OLD_ENGLISH, "Old English"},
            {Language::MIDDLE_ENGLISH, "Middle English"},
            {Language::OLD_FRENCH, "Old French"},
            {Language::OLD_GERMAN, "Old German"},
            {Language::OLD_ITALIAN, "Old Italian"},
            {Language::OLD_SPANISH, "Old Spanish"},
            {Language::OLD_PORTUGUESE, "Old Portuguese"},
            {Language::OLD_RUSSIAN, "Old Russian"},
            {Language::OLD_CHINESE, "Old Chinese"},
            {Language::OLD_JAPANESE, "Old Japanese"},
            {Language::OLD_KOREAN, "Old Korean"},
            {Language::OLD_ARABIC, "Old Arabic"},
            {Language::OLD_HINDI, "Old Hindi"},
            {Language::OLD_DUTCH, "Old Dutch"},
            {Language::OLD_SWEDISH, "Old Swedish"},
            {Language::OLD_NORWEGIAN, "Old Norwegian"},
            {Language::OLD_DANISH, "Old Danish"},
            {Language::OLD_FINNISH, "Old Finnish"},
            {Language::OLD_POLISH, "Old Polish"},
            {Language::OLD_CZECH, "Old Czech"},
            {Language::OLD_HUNGARIAN, "Old Hungarian"},
            {Language::OLD_ROMANIAN, "Old Romanian"},
            {Language::OLD_BULGARIAN, "Old Bulgarian"},
            {Language::OLD_GREEK, "Old Greek"},
            {Language::OLD_TURKISH, "Old Turkish"},
            {Language::OLD_HEBREW, "Old Hebrew"},
            {Language::OLD_PERSIAN, "Old Persian"},
            {Language::OLD_THAI, "Old Thai"},
            {Language::OLD_VIETNAMESE, "Old Vietnamese"},
            {Language::OLD_INDONESIAN, "Old Indonesian"},
            {Language::OLD_MALAY, "Old Malay"},
            {Language::OLD_FILIPINO, "Old Filipino"},
            {Language::OLD_LATIN, "Old Latin"},
            {Language::OLD_ANCIENT_GREEK, "Old Ancient Greek"},
            {Language::OLD_SANSKRIT, "Old Sanskrit"},
            {Language::OTHER, "Other"}  };
        auto it = languageMap.find(language);
        return (it != languageMap.end()) ? it->second : "Unknown";
    }

    Language stringToLanguage(const std::string& language) {
        static const std::map<std::string, Language> languageMap = {
            {"Italian", Language::ITALIAN},
            {"English", Language::ENGLISH},
            {"Spanish", Language::SPANISH},
            {"French", Language::FRENCH},
            {"German", Language::GERMAN},
            {"Portuguese", Language::PORTUGUESE},
            {"Russian", Language::RUSSIAN},
            {"Chinese", Language::CHINESE},
            {"Japanese", Language::JAPANESE},
            {"Korean", Language::KOREAN},
            {"Arabic", Language::ARABIC},
            {"Hindi", Language::HINDI},
            {"Dutch", Language::DUTCH},
            {"Swedish", Language::SWEDISH},
            {"Norwegian", Language::NORWEGIAN},
            {"Danish", Language::DANISH},
            {"Finnish", Language::FINNISH},
            {"Polish", Language::POLISH},
            {"Czech", Language::CZECH},
            {"Hungarian", Language::HUNGARIAN},
            {"Romanian", Language::ROMANIAN},
            {"Bulgarian", Language::BULGARIAN},
            {"Greek", Language::GREEK},
            {"Turkish", Language::TURKISH},
            {"Hebrew", Language::HEBREW},
            {"Persian", Language::PERSIAN},
            {"Thai", Language::THAI},
            {"Vietnamese", Language::VIETNAMESE},
            {"Indonesian", Language::INDONESIAN},
            {"Malay", Language::MALAY},
            {"Filipino", Language::FILIPINO},
            {"Latin", Language::LATIN},
            {"Ancient Greek", Language::ANCIENT_GREEK},
            {"Sanskrit", Language::SANSKRIT},
            {"Old English", Language::OLD_ENGLISH},
            {"Middle English", Language::MIDDLE_ENGLISH},
            {"Old French", Language::OLD_FRENCH},
            {"Old German", Language::OLD_GERMAN},
            {"Old Italian", Language::OLD_ITALIAN},
            {"Old Spanish", Language::OLD_SPANISH},
            {"Old Portuguese", Language::OLD_PORTUGUESE},
            {"Old Russian", Language::OLD_RUSSIAN},
            {"Old Chinese", Language::OLD_CHINESE},
            {"Old Japanese", Language::OLD_JAPANESE},
            {"Old Korean", Language::OLD_KOREAN},
            {"Old Arabic", Language::OLD_ARABIC},
            {"Old Hindi", Language::OLD_HINDI},
            {"Old Dutch", Language::OLD_DUTCH},
            {"Old Swedish", Language::OLD_SWEDISH},
            {"Old Norwegian", Language::OLD_NORWEGIAN},
            {"Old Danish", Language::OLD_DANISH},
            {"Old Finnish", Language::OLD_FINNISH},
            {"Old Polish", Language::OLD_POLISH},
            {"Old Czech", Language::OLD_CZECH},
            {"Old Hungarian", Language::OLD_HUNGARIAN},
            {"Old Romanian", Language::OLD_ROMANIAN},
            {"Old Bulgarian", Language::OLD_BULGARIAN},
            {"Old Greek", Language::OLD_GREEK},
            {"Old Turkish", Language::OLD_TURKISH},
            {"Old Hebrew", Language::OLD_HEBREW},
            {"Old Persian", Language::OLD_PERSIAN},
            {"Old Thai", Language::OLD_THAI},
            {"Old Vietnamese", Language::OLD_VIETNAMESE},
            {"Old Indonesian", Language::OLD_INDONESIAN},
            {"Old Malay", Language::OLD_MALAY},
            {"Old Filipino", Language::OLD_FILIPINO},
            {"Old Latin", Language::OLD_LATIN},
            {"Old Ancient Greek", Language::OLD_ANCIENT_GREEK},
            {"Old Sanskrit", Language::OLD_SANSKRIT},
            {"Other", Language::OTHER} };
        auto it = languageMap.find(language);
        return (it != languageMap.end()) ? it->second : Language::ENGLISH;
    }

    std::vector<std::string> getAllLanguages() {
        return {"Italian", "English", "Spanish", "French", "German", "Portuguese", "Russian", 
                "Chinese", "Japanese", "Korean", "Arabic", "Hindi", "Dutch", "Swedish", 
                "Norwegian", "Danish", "Finnish", "Polish", "Czech", "Hungarian", "Romanian", 
                "Bulgarian", "Greek", "Turkish", "Hebrew", "Persian", "Thai", "Vietnamese", 
                "Indonesian", "Malay", "Filipino", "Latin", "Ancient Greek", "Sanskrit", 
                "Old English", "Middle English", "Old French", "Old German", "Old Italian", 
                "Old Spanish", "Old Portuguese", "Old Russian", "Old Chinese", "Old Japanese", 
                "Old Korean", "Old Arabic", "Old Hindi", "Old Dutch", "Old Swedish", 
                "Old Norwegian", "Old Danish", "Old Finnish", "Old Polish", "Old Czech", 
                "Old Hungarian", "Old Romanian", "Old Bulgarian", "Old Greek", "Old Turkish", 
                "Old Hebrew", "Old Persian", "Old Thai", "Old Vietnamese", "Old Indonesian", 
                "Old Malay", "Old Filipino", "Old Latin", "Old Ancient Greek", "Old Sanskrit", "Other"};
    }
} 