#############################################################################
# Makefile for building: build/bin/MultimediaLibrary
# Generated by qmake (3.1) (Qt 6.2.4)
# Project:  MultimediaLibrary.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile MultimediaLibrary.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DUSE_QT -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_SVG_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -std=c++17 -Wall -Wextra -O2 -std=gnu++1z -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Isrc/Backend/Elements -Isrc/Backend/Enums -Isrc/Backend/Library -Isrc/Frontend/Windows -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtSvg -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = MultimediaLibrary1.0.0
DISTDIR = /home/student/Documents/MultimediaLibrary/.tmp/MultimediaLibrary1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath-link,/usr/lib/x86_64-linux-gnu
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt6Widgets.so /usr/lib/x86_64-linux-gnu/libQt6Svg.so /usr/lib/x86_64-linux-gnu/libGL.so /usr/lib/x86_64-linux-gnu/libQt6Gui.so /usr/lib/x86_64-linux-gnu/libGLX.so /usr/lib/x86_64-linux-gnu/libOpenGL.so /usr/lib/x86_64-linux-gnu/libQt6Core.so -lpthread -lGLX -lOpenGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/Backend/Elements/Date.cpp \
		src/Backend/Elements/Media.cpp \
		src/Backend/Elements/Book.cpp \
		src/Backend/Elements/Movie.cpp \
		src/Backend/Elements/Song.cpp \
		src/Backend/Elements/Magazine.cpp \
		src/Backend/Elements/Podcast.cpp \
		src/Backend/Enums/Genres.cpp \
		src/Backend/Enums/Languages.cpp \
		src/Backend/Library/Library.cpp \
		src/Backend/Persistence/JsonPersistence.cpp \
		src/Backend/Persistence/XmlPersistence.cpp \
		src/Frontend/Windows/MainWindow.cpp \
		src/Frontend/Windows/MediaCard.cpp \
		src/Frontend/Windows/AddMediaDialog.cpp \
		src/Frontend/Windows/SearchDialog.cpp qrc_resources.cpp \
		moc_MainWindow.cpp \
		moc_MediaCard.cpp \
		moc_AddMediaDialog.cpp \
		moc_SearchDialog.cpp
OBJECTS       = main.o \
		Date.o \
		Media.o \
		Book.o \
		Movie.o \
		Song.o \
		Magazine.o \
		Podcast.o \
		Genres.o \
		Languages.o \
		Library.o \
		JsonPersistence.o \
		XmlPersistence.o \
		MainWindow.o \
		MediaCard.o \
		AddMediaDialog.o \
		SearchDialog.o \
		qrc_resources.o \
		moc_MainWindow.o \
		moc_MediaCard.o \
		moc_AddMediaDialog.o \
		moc_SearchDialog.o
DIST          = /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_chartsqml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/lex.prf \
		MultimediaLibrary.pro src/Backend/Elements/Date.h \
		src/Backend/Elements/Media.h \
		src/Backend/Elements/MediaVisitor.h \
		src/Backend/Elements/Book.h \
		src/Backend/Elements/Movie.h \
		src/Backend/Elements/Song.h \
		src/Backend/Elements/Magazine.h \
		src/Backend/Elements/Podcast.h \
		src/Backend/Enums/Genres.h \
		src/Backend/Enums/Languages.h \
		src/Backend/Library/Library.h \
		src/Backend/Persistence/IPersistence.h \
		src/Backend/Persistence/JsonPersistence.h \
		src/Backend/Persistence/XmlPersistence.h \
		src/Frontend/Windows/MainWindow.h \
		src/Frontend/Windows/MediaCard.h \
		src/Frontend/Windows/AddMediaDialog.h \
		src/Frontend/Windows/SearchDialog.h src/main.cpp \
		src/Backend/Elements/Date.cpp \
		src/Backend/Elements/Media.cpp \
		src/Backend/Elements/Book.cpp \
		src/Backend/Elements/Movie.cpp \
		src/Backend/Elements/Song.cpp \
		src/Backend/Elements/Magazine.cpp \
		src/Backend/Elements/Podcast.cpp \
		src/Backend/Enums/Genres.cpp \
		src/Backend/Enums/Languages.cpp \
		src/Backend/Library/Library.cpp \
		src/Backend/Persistence/JsonPersistence.cpp \
		src/Backend/Persistence/XmlPersistence.cpp \
		src/Frontend/Windows/MainWindow.cpp \
		src/Frontend/Windows/MediaCard.cpp \
		src/Frontend/Windows/AddMediaDialog.cpp \
		src/Frontend/Windows/SearchDialog.cpp
QMAKE_TARGET  = MultimediaLibrary
DESTDIR       = build/bin/
TARGET        = build/bin/MultimediaLibrary


first: all
####### Build rules

build/bin/MultimediaLibrary:  $(OBJECTS)  
	@test -d build/bin/ || mkdir -p build/bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MultimediaLibrary.pro /usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_chartsqml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/lex.prf \
		MultimediaLibrary.pro \
		resources.qrc \
		/usr/lib/x86_64-linux-gnu/libQt6Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt6Svg.prl \
		/usr/lib/x86_64-linux-gnu/libQt6Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt6Core.prl
	$(QMAKE) -o Makefile MultimediaLibrary.pro
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_chartsqml.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_svgwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/lex.prf:
MultimediaLibrary.pro:
resources.qrc:
/usr/lib/x86_64-linux-gnu/libQt6Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt6Svg.prl:
/usr/lib/x86_64-linux-gnu/libQt6Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile MultimediaLibrary.pro

qmake_all: FORCE


all: Makefile build/bin/MultimediaLibrary

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/Backend/Elements/Date.h src/Backend/Elements/Media.h src/Backend/Elements/MediaVisitor.h src/Backend/Elements/Book.h src/Backend/Elements/Movie.h src/Backend/Elements/Song.h src/Backend/Elements/Magazine.h src/Backend/Elements/Podcast.h src/Backend/Enums/Genres.h src/Backend/Enums/Languages.h src/Backend/Library/Library.h src/Backend/Persistence/IPersistence.h src/Backend/Persistence/JsonPersistence.h src/Backend/Persistence/XmlPersistence.h src/Frontend/Windows/MainWindow.h src/Frontend/Windows/MediaCard.h src/Frontend/Windows/AddMediaDialog.h src/Frontend/Windows/SearchDialog.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/Backend/Elements/Date.cpp src/Backend/Elements/Media.cpp src/Backend/Elements/Book.cpp src/Backend/Elements/Movie.cpp src/Backend/Elements/Song.cpp src/Backend/Elements/Magazine.cpp src/Backend/Elements/Podcast.cpp src/Backend/Enums/Genres.cpp src/Backend/Enums/Languages.cpp src/Backend/Library/Library.cpp src/Backend/Persistence/JsonPersistence.cpp src/Backend/Persistence/XmlPersistence.cpp src/Frontend/Windows/MainWindow.cpp src/Frontend/Windows/MediaCard.cpp src/Frontend/Windows/AddMediaDialog.cpp src/Frontend/Windows/SearchDialog.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		/usr/lib/qt6/libexec/rcc \
		src/Frontend/Resources/icons/movie.svg \
		src/Frontend/Resources/icons/sort_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.svg \
		src/Frontend/Resources/icons/all.svg \
		src/Frontend/Resources/icons/music.svg \
		src/Frontend/Resources/icons/add.svg \
		src/Frontend/Resources/icons/appicon.svg \
		src/Frontend/Resources/icons/magazine.svg \
		src/Frontend/Resources/icons/search.svg \
		src/Frontend/Resources/icons/filter-advanced.svg \
		src/Frontend/Resources/icons/export.svg \
		src/Frontend/Resources/icons/filter-clear.svg \
		src/Frontend/Resources/icons/edit.svg \
		src/Frontend/Resources/icons/delete.svg \
		src/Frontend/Resources/icons/book.svg \
		src/Frontend/Resources/icons/import.svg \
		src/Frontend/Resources/icons/back.svg \
		src/Frontend/Resources/icons/podcast.svg \
		src/Frontend/Resources/icons/save.svg
	/usr/lib/qt6/libexec/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp
	g++ -pipe -std=c++17 -Wall -Wextra -O2 -std=gnu++1z -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_MainWindow.cpp moc_MediaCard.cpp moc_AddMediaDialog.cpp moc_SearchDialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_MainWindow.cpp moc_MediaCard.cpp moc_AddMediaDialog.cpp moc_SearchDialog.cpp
moc_MainWindow.cpp: src/Frontend/Windows/MainWindow.h \
		src/Backend/Elements/Media.h \
		src/Backend/Elements/Date.h \
		src/Backend/Enums/Genres.h \
		src/Backend/Enums/Languages.h \
		src/Backend/Elements/MediaVisitor.h \
		src/Backend/Elements/Book.h \
		src/Backend/Elements/Movie.h \
		src/Backend/Elements/Song.h \
		src/Backend/Elements/Magazine.h \
		src/Backend/Elements/Podcast.h \
		src/Backend/Library/Library.h \
		src/Frontend/Windows/MediaCard.h \
		src/Frontend/Windows/AddMediaDialog.h \
		src/Frontend/Windows/SearchDialog.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/student/Documents/MultimediaLibrary/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/student/Documents/MultimediaLibrary -I/home/student/Documents/MultimediaLibrary/src/Backend/Elements -I/home/student/Documents/MultimediaLibrary/src/Backend/Enums -I/home/student/Documents/MultimediaLibrary/src/Backend/Library -I/home/student/Documents/MultimediaLibrary/src/Frontend/Windows -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtSvg -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/Frontend/Windows/MainWindow.h -o moc_MainWindow.cpp

moc_MediaCard.cpp: src/Frontend/Windows/MediaCard.h \
		src/Backend/Elements/Media.h \
		src/Backend/Elements/Date.h \
		src/Backend/Enums/Genres.h \
		src/Backend/Enums/Languages.h \
		src/Backend/Elements/MediaVisitor.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/student/Documents/MultimediaLibrary/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/student/Documents/MultimediaLibrary -I/home/student/Documents/MultimediaLibrary/src/Backend/Elements -I/home/student/Documents/MultimediaLibrary/src/Backend/Enums -I/home/student/Documents/MultimediaLibrary/src/Backend/Library -I/home/student/Documents/MultimediaLibrary/src/Frontend/Windows -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtSvg -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/Frontend/Windows/MediaCard.h -o moc_MediaCard.cpp

moc_AddMediaDialog.cpp: src/Frontend/Windows/AddMediaDialog.h \
		src/Backend/Elements/Media.h \
		src/Backend/Elements/Date.h \
		src/Backend/Enums/Genres.h \
		src/Backend/Enums/Languages.h \
		src/Backend/Elements/MediaVisitor.h \
		src/Backend/Elements/Book.h \
		src/Backend/Elements/Movie.h \
		src/Backend/Elements/Song.h \
		src/Backend/Elements/Magazine.h \
		src/Backend/Elements/Podcast.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/student/Documents/MultimediaLibrary/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/student/Documents/MultimediaLibrary -I/home/student/Documents/MultimediaLibrary/src/Backend/Elements -I/home/student/Documents/MultimediaLibrary/src/Backend/Enums -I/home/student/Documents/MultimediaLibrary/src/Backend/Library -I/home/student/Documents/MultimediaLibrary/src/Frontend/Windows -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtSvg -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/Frontend/Windows/AddMediaDialog.h -o moc_AddMediaDialog.cpp

moc_SearchDialog.cpp: src/Frontend/Windows/SearchDialog.h \
		src/Backend/Enums/Genres.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/student/Documents/MultimediaLibrary/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/student/Documents/MultimediaLibrary -I/home/student/Documents/MultimediaLibrary/src/Backend/Elements -I/home/student/Documents/MultimediaLibrary/src/Backend/Enums -I/home/student/Documents/MultimediaLibrary/src/Backend/Library -I/home/student/Documents/MultimediaLibrary/src/Frontend/Windows -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtSvg -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/Frontend/Windows/SearchDialog.h -o moc_SearchDialog.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: src/main.cpp src/Frontend/Windows/MainWindow.h \
		src/Backend/Elements/Media.h \
		src/Backend/Elements/Date.h \
		src/Backend/Enums/Genres.h \
		src/Backend/Enums/Languages.h \
		src/Backend/Elements/MediaVisitor.h \
		src/Backend/Elements/Book.h \
		src/Backend/Elements/Movie.h \
		src/Backend/Elements/Song.h \
		src/Backend/Elements/Magazine.h \
		src/Backend/Elements/Podcast.h \
		src/Backend/Library/Library.h \
		src/Frontend/Windows/MediaCard.h \
		src/Frontend/Windows/AddMediaDialog.h \
		src/Frontend/Windows/SearchDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

Date.o: src/Backend/Elements/Date.cpp src/Backend/Elements/Date.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Date.o src/Backend/Elements/Date.cpp

Media.o: src/Backend/Elements/Media.cpp src/Backend/Elements/Media.h \
		src/Backend/Elements/Date.h \
		src/Backend/Enums/Genres.h \
		src/Backend/Enums/Languages.h \
		src/Backend/Elements/MediaVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Media.o src/Backend/Elements/Media.cpp

Book.o: src/Backend/Elements/Book.cpp src/Backend/Elements/Book.h \
		src/Backend/Elements/Media.h \
		src/Backend/Elements/Date.h \
		src/Backend/Enums/Genres.h \
		src/Backend/Enums/Languages.h \
		src/Backend/Elements/MediaVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Book.o src/Backend/Elements/Book.cpp

Movie.o: src/Backend/Elements/Movie.cpp src/Backend/Elements/Movie.h \
		src/Backend/Elements/Media.h \
		src/Backend/Elements/Date.h \
		src/Backend/Enums/Genres.h \
		src/Backend/Enums/Languages.h \
		src/Backend/Elements/MediaVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Movie.o src/Backend/Elements/Movie.cpp

Song.o: src/Backend/Elements/Song.cpp src/Backend/Elements/Song.h \
		src/Backend/Elements/Media.h \
		src/Backend/Elements/Date.h \
		src/Backend/Enums/Genres.h \
		src/Backend/Enums/Languages.h \
		src/Backend/Elements/MediaVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Song.o src/Backend/Elements/Song.cpp

Magazine.o: src/Backend/Elements/Magazine.cpp src/Backend/Elements/Magazine.h \
		src/Backend/Elements/Media.h \
		src/Backend/Elements/Date.h \
		src/Backend/Enums/Genres.h \
		src/Backend/Enums/Languages.h \
		src/Backend/Elements/MediaVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Magazine.o src/Backend/Elements/Magazine.cpp

Podcast.o: src/Backend/Elements/Podcast.cpp src/Backend/Elements/Podcast.h \
		src/Backend/Elements/Media.h \
		src/Backend/Elements/Date.h \
		src/Backend/Enums/Genres.h \
		src/Backend/Enums/Languages.h \
		src/Backend/Elements/MediaVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Podcast.o src/Backend/Elements/Podcast.cpp

Genres.o: src/Backend/Enums/Genres.cpp src/Backend/Enums/Genres.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Genres.o src/Backend/Enums/Genres.cpp

Languages.o: src/Backend/Enums/Languages.cpp src/Backend/Enums/Languages.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Languages.o src/Backend/Enums/Languages.cpp

Library.o: src/Backend/Library/Library.cpp src/Backend/Library/Library.h \
		src/Backend/Persistence/JsonPersistence.h \
		src/Backend/Persistence/IPersistence.h \
		src/Backend/Persistence/XmlPersistence.h \
		src/Backend/Elements/Media.h \
		src/Backend/Elements/Date.h \
		src/Backend/Enums/Genres.h \
		src/Backend/Enums/Languages.h \
		src/Backend/Elements/MediaVisitor.h \
		src/Backend/Elements/Book.h \
		src/Backend/Elements/Movie.h \
		src/Backend/Elements/Song.h \
		src/Backend/Elements/Magazine.h \
		src/Backend/Elements/Podcast.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Library.o src/Backend/Library/Library.cpp

JsonPersistence.o: src/Backend/Persistence/JsonPersistence.cpp src/Backend/Persistence/JsonPersistence.h \
		src/Backend/Persistence/IPersistence.h \
		src/Backend/Library/Library.h \
		src/Backend/Elements/Book.h \
		src/Backend/Elements/Media.h \
		src/Backend/Elements/Date.h \
		src/Backend/Enums/Genres.h \
		src/Backend/Enums/Languages.h \
		src/Backend/Elements/MediaVisitor.h \
		src/Backend/Elements/Movie.h \
		src/Backend/Elements/Song.h \
		src/Backend/Elements/Magazine.h \
		src/Backend/Elements/Podcast.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o JsonPersistence.o src/Backend/Persistence/JsonPersistence.cpp

XmlPersistence.o: src/Backend/Persistence/XmlPersistence.cpp src/Backend/Persistence/XmlPersistence.h \
		src/Backend/Persistence/IPersistence.h \
		src/Backend/Library/Library.h \
		src/Backend/Elements/Book.h \
		src/Backend/Elements/Media.h \
		src/Backend/Elements/Date.h \
		src/Backend/Enums/Genres.h \
		src/Backend/Enums/Languages.h \
		src/Backend/Elements/MediaVisitor.h \
		src/Backend/Elements/Movie.h \
		src/Backend/Elements/Song.h \
		src/Backend/Elements/Magazine.h \
		src/Backend/Elements/Podcast.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o XmlPersistence.o src/Backend/Persistence/XmlPersistence.cpp

MainWindow.o: src/Frontend/Windows/MainWindow.cpp src/Frontend/Windows/MainWindow.h \
		src/Backend/Elements/Media.h \
		src/Backend/Elements/Date.h \
		src/Backend/Enums/Genres.h \
		src/Backend/Enums/Languages.h \
		src/Backend/Elements/MediaVisitor.h \
		src/Backend/Elements/Book.h \
		src/Backend/Elements/Movie.h \
		src/Backend/Elements/Song.h \
		src/Backend/Elements/Magazine.h \
		src/Backend/Elements/Podcast.h \
		src/Backend/Library/Library.h \
		src/Frontend/Windows/MediaCard.h \
		src/Frontend/Windows/AddMediaDialog.h \
		src/Frontend/Windows/SearchDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o src/Frontend/Windows/MainWindow.cpp

MediaCard.o: src/Frontend/Windows/MediaCard.cpp src/Frontend/Windows/MediaCard.h \
		src/Backend/Elements/Media.h \
		src/Backend/Elements/Date.h \
		src/Backend/Enums/Genres.h \
		src/Backend/Enums/Languages.h \
		src/Backend/Elements/MediaVisitor.h \
		src/Backend/Elements/Book.h \
		src/Backend/Elements/Movie.h \
		src/Backend/Elements/Song.h \
		src/Backend/Elements/Magazine.h \
		src/Backend/Elements/Podcast.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MediaCard.o src/Frontend/Windows/MediaCard.cpp

AddMediaDialog.o: src/Frontend/Windows/AddMediaDialog.cpp src/Frontend/Windows/AddMediaDialog.h \
		src/Backend/Elements/Media.h \
		src/Backend/Elements/Date.h \
		src/Backend/Enums/Genres.h \
		src/Backend/Enums/Languages.h \
		src/Backend/Elements/MediaVisitor.h \
		src/Backend/Elements/Book.h \
		src/Backend/Elements/Movie.h \
		src/Backend/Elements/Song.h \
		src/Backend/Elements/Magazine.h \
		src/Backend/Elements/Podcast.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AddMediaDialog.o src/Frontend/Windows/AddMediaDialog.cpp

SearchDialog.o: src/Frontend/Windows/SearchDialog.cpp src/Frontend/Windows/SearchDialog.h \
		src/Backend/Enums/Genres.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SearchDialog.o src/Frontend/Windows/SearchDialog.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

moc_MediaCard.o: moc_MediaCard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MediaCard.o moc_MediaCard.cpp

moc_AddMediaDialog.o: moc_AddMediaDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AddMediaDialog.o moc_AddMediaDialog.cpp

moc_SearchDialog.o: moc_SearchDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SearchDialog.o moc_SearchDialog.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

